<a href="https://colab.research.google.com/github/rajivdahal/10daysml/blob/master/NLP_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import nltk

In [ ]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
from nltk.corpus import stopwords

In [ ]:
stopwords.words('english')

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

generally in NLP, stopwords needs to be removed. but if you are doing sentimental analysis not or negative words has some meaning/importance so do not remove such words

In [ ]:
#creating my own stopwords list
from nltk.corpus import stopwords
imported_stopwords = stopwords.words('english')
for word in ['not','nor']:
  if word in imported_stopwords:
      imported_stopwords.remove(word)
print(imported_stopwords)

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'only', 'own', 'same', 'so', 'than', 'too', 'very', 

In [ ]:
from nltk.stem import PorterStemmer, WordNetLemmatizer
from nltk.tokenize import sent_tokenize,word_tokenize
nltk.download('punkt')
nltk.download('wordnet')
corpus = []
lemmetizedCorpus = []
paragraph = "I love learning data science. I am just testing this feature"
stem_tokenized_paragraph = sent_tokenize(paragraph)
imported_stopwords = stopwords.words('english')
for i in range(len(stem_tokenized_paragraph)):
  tokenizedWords = word_tokenize(stem_tokenized_paragraph[i])
  stemmedWords = [PorterStemmer().stem(word) for word in tokenizedWords if not word in imported_stopwords]
  print('stemword is', stemmedWords)
  corpus.append(' '.join(stemmedWords))
print('corpus is', corpus)

#the same thing you can do using lemmetizer

for i in range(len(stem_tokenized_paragraph)):
  tokenizedWords = word_tokenize(stem_tokenized_paragraph[i])
  lemmetizedWords = [WordNetLemmatizer().lemmatize(word) for word in tokenizedWords if not word in imported_stopwords]
  print('stemword for lemmetized is', lemmetizedWords)
  lemmetizedCorpus.append(' '.join(lemmetizedWords))
print('lemmetizedCorpus is', lemmetizedCorpus)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


stemword is ['i', 'love', 'learn', 'data', 'scienc', '.']
stemword is ['i', 'test', 'featur']
corpus is ['i love learn data scienc .', 'i test featur']
stemword for lemmetized is ['I', 'love', 'learning', 'data', 'science', '.']
stemword for lemmetized is ['I', 'testing', 'feature']
lemmetizedCorpus is ['I love learning data science .', 'I testing feature']


In [ ]:
#the same thing you can do using lammetizer

In [ ]:
!pip install -U scikit-learn

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.4/13.4 MB 20.3 MB/s eta 0:00:00
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.3.2
    Uninstalling scikit-learn-1.3.2:
      Successfully uninstalled scikit-learn-1.3.2


**Implementation of preprocessiong step2**

In [2]:
#bag of words

# Preprocessing1
paragraph = """
Nepal,[a] officially the Federal Democratic Republic of Nepal,[b] is a landlocked country in South Asia. It is mainly situated in the Himalayas, but also includes parts of the Indo-Gangetic Plain. It borders the Tibet Autonomous Region of China to the north, and India to the south, east, and west, while it is narrowly separated from Bangladesh by the Siliguri Corridor, and from Bhutan by the Indian state of Sikkim. Nepal has a diverse geography, including fertile plains, subalpine forested hills, and eight of the world's ten tallest mountains, including Mount Everest, the highest point on Earth. Kathmandu is the nation's capital and the largest city. Nepal is a multi-ethnic, multi-lingual, multi-religious and multi-cultural state, with Nepali as the official language.

The name "Nepal" is first recorded in texts from the Vedic period of the Indian subcontinent, the era in ancient Nepal when Hinduism was founded, the predominant religion of the country. In the middle of the first millennium BC, Gautama Buddha, the founder of Buddhism, was born in Lumbini in southern Nepal. Parts of northern Nepal were intertwined with the culture of Tibet. The centrally located Kathmandu Valley is intertwined with the culture of Indo-Aryans, and was the seat of the prosperous Newar confederacy known as Nepal Mandala. The Himalayan branch of the ancient Silk Road was dominated by the valley's traders. The cosmopolitan region developed distinct traditional art and architecture. By the 18th century, the Gorkha Kingdom achieved the unification of Nepal. The Shah dynasty established the Kingdom of Nepal and later formed an alliance with the British Empire, under its Rana dynasty of premiers. The country was never colonised but served as a buffer state between Imperial China and British India. Parliamentary democracy was introduced in 1951 but was twice suspended by Nepalese monarchs, in 1960 and 2005. The Nepalese Civil War in the 1990s and early 2000s resulted in the establishment of a secular republic in 2008, ending the world's last Hindu monarchy.
 """

In [23]:
import nltk
from nltk.stem import PorterStemmer, WordNetLemmatizer
from nltk.tokenize import sent_tokenize,word_tokenize
from nltk.corpus import stopwords
import re
from sklearn.feature_extraction.text import CountVectorizer
import numpy as np
import sys
def vectorizeParagraph(paragraph, vectorizer):
  nltk.download('punkt')
  nltk.download('wordnet')
  nltk.download('stopwords')
  paragraph_sentence_list = sent_tokenize(paragraph)
  corpus = []
  imported_stopwords = stopwords.words('english')
  for i in range(len(paragraph_sentence_list)):
    cleaned_sentence = re.sub('[^a-zA-Z0-9]',' ', paragraph_sentence_list[i])
    tokenized_words = word_tokenize(cleaned_sentence)
    stemmed_words = [WordNetLemmatizer().lemmatize(word) for word in tokenized_words if not word in imported_stopwords]
    corpus.append(' '.join(stemmed_words))

  #we are going to apply bag of words in corpus to this we need to use countvectorizer from sklearn feature extraction
  print('corpus is', corpus)

  vectorized = vectorizer.fit_transform(corpus)
  np.set_printoptions(threshold=sys.maxsize)
  print(vectorized.toarray())
  return vectorized


vectorizer = CountVectorizer()
vectorizeParagraph(paragraph, vectorizer)


#problem here is it is not that robust in




corpus is ['Nepal officially Federal Democratic Republic Nepal b landlocked country South Asia', 'It mainly situated Himalayas also includes part Indo Gangetic Plain', 'It border Tibet Autonomous Region China north India south east west narrowly separated Bangladesh Siliguri Corridor Bhutan Indian state Sikkim', 'Nepal diverse geography including fertile plain subalpine forested hill eight world ten tallest mountain including Mount Everest highest point Earth', 'Kathmandu nation capital largest city', 'Nepal multi ethnic multi lingual multi religious multi cultural state Nepali official language', 'The name Nepal first recorded text Vedic period Indian subcontinent era ancient Nepal Hinduism founded predominant religion country', 'In middle first millennium BC Gautama Buddha founder Buddhism born Lumbini southern Nepal', 'Parts northern Nepal intertwined culture Tibet', 'The centrally located Kathmandu Valley intertwined culture Indo Aryans seat prosperous Newar confederacy known Nepal

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


<17x163 sparse matrix of type '<class 'numpy.int64'>'
	with 201 stored elements in Compressed Sparse Row format>

In [31]:
def getBagOfWordsFeaturesNames(vectorizer):
  return vectorizer.get_feature_names_out()
def getVocabulary(vectorizer):
  return vectorizer.vocabulary_

In [35]:
vectorizer = CountVectorizer(ngram_range= (1, 1))
paragraph = 'good boy. good girl. Boy and girl good'
vectorizeParagraph(paragraph, vectorizer)

corpus is ['good boy', 'good girl', 'Boy girl good']
[[1 0 1]
 [0 1 1]
 [1 1 1]]


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


<3x3 sparse matrix of type '<class 'numpy.int64'>'
	with 7 stored elements in Compressed Sparse Row format>

In [36]:
getBagOfWordsFeaturesNames(vectorizer)

array(['boy', 'girl', 'good'], dtype=object)

In [38]:
getVocabulary(vectorizer)
# returns unique vocabulary with index of it

{'good': 2, 'boy': 0, 'girl': 1}

**Term frequency - Inverse document frequency(TF-IDF) Implementation**

In [40]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
paragraph = """
Nepal,[a] officially the Federal Democratic Republic of Nepal,[b] is a landlocked country in South Asia. It is mainly situated in the Himalayas, but also includes parts of the Indo-Gangetic Plain. It borders the Tibet Autonomous Region of China to the north, and India to the south, east, and west, while it is narrowly separated from Bangladesh by the Siliguri Corridor, and from Bhutan by the Indian state of Sikkim. Nepal has a diverse geography, including fertile plains, subalpine forested hills, and eight of the world's ten tallest mountains, including Mount Everest, the highest point on Earth. Kathmandu is the nation's capital and the largest city. Nepal is a multi-ethnic, multi-lingual, multi-religious and multi-cultural state, with Nepali as the official language.

The name "Nepal" is first recorded in texts from the Vedic period of the Indian subcontinent, the era in ancient Nepal when Hinduism was founded, the predominant religion of the country. In the middle of the first millennium BC, Gautama Buddha, the founder of Buddhism, was born in Lumbini in southern Nepal. Parts of northern Nepal were intertwined with the culture of Tibet. The centrally located Kathmandu Valley is intertwined with the culture of Indo-Aryans, and was the seat of the prosperous Newar confederacy known as Nepal Mandala. The Himalayan branch of the ancient Silk Road was dominated by the valley's traders. The cosmopolitan region developed distinct traditional art and architecture. By the 18th century, the Gorkha Kingdom achieved the unification of Nepal. The Shah dynasty established the Kingdom of Nepal and later formed an alliance with the British Empire, under its Rana dynasty of premiers. The country was never colonised but served as a buffer state between Imperial China and British India. Parliamentary democracy was introduced in 1951 but was twice suspended by Nepalese monarchs, in 1960 and 2005. The Nepalese Civil War in the 1990s and early 2000s resulted in the establishment of a secular republic in 2008, ending the world's last Hindu monarchy.
 """
X = vectorizeParagraph(paragraph, vectorizer)
print('features are', vectorizer.get_feature_names_out())
print(X.shape)

corpus is ['Nepal officially Federal Democratic Republic Nepal b landlocked country South Asia', 'It mainly situated Himalayas also includes part Indo Gangetic Plain', 'It border Tibet Autonomous Region China north India south east west narrowly separated Bangladesh Siliguri Corridor Bhutan Indian state Sikkim', 'Nepal diverse geography including fertile plain subalpine forested hill eight world ten tallest mountain including Mount Everest highest point Earth', 'Kathmandu nation capital largest city', 'Nepal multi ethnic multi lingual multi religious multi cultural state Nepali official language', 'The name Nepal first recorded text Vedic period Indian subcontinent era ancient Nepal Hinduism founded predominant religion country', 'In middle first millennium BC Gautama Buddha founder Buddhism born Lumbini southern Nepal', 'Parts northern Nepal intertwined culture Tibet', 'The centrally located Kathmandu Valley intertwined culture Indo Aryans seat prosperous Newar confederacy known Nepal

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
