In [8]:
import numpy as np
arr=np.linspace(2,10,5)

In [5]:
arr

array([ 2.,  4.,  6.,  8., 10.])

In [6]:
arr1=arr.copy()
arr1

array([ 2.,  4.,  6.,  8., 10.])

In [10]:
arr1=np.arange(6).reshape(3,2)
arr1

array([[0, 1],
       [2, 3],
       [4, 5]])

In [11]:
arr2=np.arange(4).reshape(2,2)
arr2

array([[0, 1],
       [2, 3]])

In [12]:
np.vstack((arr1,arr2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [0, 1],
       [2, 3]])

In [14]:
arr1

array([[0, 1],
       [2, 3],
       [4, 5]])

In [20]:
np.hsplit(arr1,2)

[array([[0],
        [2],
        [4]]),
 array([[1],
        [3],
        [5]])]